### ISSUE TITLE
Make print messages optional

### ISSUE THREAD

**Issue by Stoeoeoe** [willnationsdev/godot-inheritance-dock#3]
Hi!

I have a little suggestion. As an addon dev myself, I can understand that there are a couple of debug/print messages in your code. However, as an end user, I usually don't really care about them - I just assume that the plugin does its job.

Would it be possible to add a configuration value to the `godot_inheritance_dock.cfg` which would allow to disable and enable all print messages? I would have done it myself, but I'd like to hear your opinion about it!

On another note, I made a pull request to fix an issue when disabling the plugin! :)

**Comment by willnationsdev** [comment]
Oh whoops. Yeah, I meant to remove ALL debug / print messages when I converted it from a test project to an add-on repository.

Making it so that the config prints them optionally is actually a really good idea though. I hadn't thought of that. I'll have to change that when I get a chance. Don't have wifi as I just moved into a new house, but I'll try to fix it when I can. Thanks for letting me know!

Also, thank you for the PR! I'll take a look at it once you've submitted it. :-)

**Comment by willnationsdev** [comment]
I removed the print messages that do not indicate significant problems (it still prints a warning if the config doesn't load, etc.). I may try to tackle this in the future though if people want it, but I'd need an idea of what all information people want printed. Options such as when does ti scan the file system, which files are regex filtered and how, what data is examined when the extend/open/create/instance buttons are pressed, etc. I'm generally moving on to other projects though.

**Comment by willnationsdev** [comment]
Hmm...my guess is that in general, people won't need to add this functionality now that I've removed all of the unnecessary print messages. I'm just going to close this and it can be re-opened if people actually end up needing to do such in-depth debugging again. After all, if you're already doing in-depth debugging, might as well implement this Issue while we're at it and not have to re-do the work.
